### ISSUE TITLE
Fix Visual Editing in Sanity

### ISSUE THREAD

**Issue by ozgurcoban** [ozgurcoban/digital-studio#1]
Resolve issues with the visual editing experience to ensure non-technical users can make changes easily.

app/(admin)/layout.tsx

![Image](https://github.com/user-attachments/assets/dcb59cc7-11b1-4bed-9092-e3370b3b0163)

**Comment by MARSIF123** [comment]
In your case, since the (admin) route holds the Sanity Studio itself and the (site) route is where you want to integrate Visual Editing, you do not need to import or use VisualEditing in (admin)/layout.tsx. Here's why:

**(admin) Route:** This is where the actual Sanity Studio exists. Visual Editing is not needed here because it is primarily for the content editing interface (e.g., for you or your team to manage content).
**(site) Route:** This is the part of the site where visitors will see the content, and this is where Visual Editing is required to connect the frontend to Sanity’s content preview. So, the VisualEditing component should be used here.

You need to move this chunk of code 

`import { VisualEditing } from "next-sanity";`
`import { draftMode } from "next/headers";`
`<body>`
`{draftMode().isEnabled && (`
          `<a`
           ` className="fixed right-0 bottom-0 bg-blue-500 text-white p-4 m-4"`
           ` href="/api/draft-mode/disable"`
         ` >`
           ` Disable preview mode`
         ` </a>`
       ` )}`

`{draftMode().isEnabled && <VisualEditing />}`
 `</body>`

from (admin)/layout.tsx to (site)/layout.tsx and it will fix the issue.
