### ISSUE TITLE
Fix: Fetching Images from Sanity with Custom SanityImage Component

### ISSUE THREAD

**Issue by ozgurcoban** [ozgurcoban/digital-studio#2]
There is a TypeScript issue with rendering images in Posts.tsx. It appears that there may be a misconfiguration in how the SanityImage component is receiving data.

- **Problem:** The SanityImage component is not correctly handling the image props, which results in improper rendering within the Posts.tsx file.

- **Objective:** Diagnose and resolve the TypeScript misconfiguration, ensuring that the SanityImage component properly handles data across various use cases.

Additionally, consider refactoring the function to make the SanityImage component more versatile and reusable throughout the site. This will simplify integrating SanityImage in multiple components, ensuring consistency and ease of use.

**Comment by MARSIF123** [comment]
In the Sanity image component, we should avoid using the spread operator for props. Since we're explicitly defining the `SanityImageProps` type, we should only use the props specified within that type. If we try to pass any additional props that aren't defined in SanityImageProps, it will result in an error.

In my opinion, the most essential props are:

`type SanityImageProps = {`
 ` src: SanityImageSource;`
`  className?: string;`
`};`
**src**: This is, of course, for the image source.
**className**: Optional, but useful for styling the image.

By sticking to these two props, we ensure that the component is clean and predictable, and any unnecessary or invalid props are caught during development.

The code Posts.tsx  should be :

` {/* Background Image */}`
`                {mainImage?.asset && <SanityImage`
`                  src={mainImage}`
 `                 className="absolute inset-0 z-0 rounded"`
`                /> }`

Always ensure image is not null before rendering SanityImage as the `SanityImageSource` can not be null.
